### ISSUE TITLE
Why does an array of notes play as a chord ?

### ISSUE THREAD

**Issue by raff** [jsrmath/sharp11-web-audio#1]
More of a question than an issue, but why did you make the array of notes work more like a chord (play all notes together) instead of more like a scale (play notes consecutively) ?

I wanted to play chord notes more like an "arpeggio" (one after another) but I can't really do it unless I implement my own "play a sequence" method.

But this (and sharp11) is great! Thanks!

**Comment by jsrmath** [comment]
The reason is that I wrote this library specifically for the [Sharp11 Web Front-end](https://github.com/jsrmath/sharp11-client), which necessitated having a function that played an array of notes together, but did not necessitate playing an array of notes in sequence.  I don't currently see an elegant way of including this functionality without refactoring the way the module works, but I might consider doing that at some point.

**Comment by raff** [comment]
You could add, for example, a new method playSequence, that is similar to play but always play chords and arrays as sequences, like scales. 

Thanks!

-- Raffaele

**Comment by jsrmath** [comment]
I could, but I don't like the idea of making a new function that special cases one thing when the rest of the module is designed to be very polymorphic based on Sharp11 types.

**Comment by raff** [comment]
I am not sure I understand where it would not be polymorphic. I was
thinking of something like
https://gist.github.com/raff/52e2fb759c0b218349b5356161828d0c

Anyway, I can always implement that myself. Thanks for getting back to me.

-- Raffaele

**Comment by jsrmath** [comment]
Ah, I see.  I would be okay with adding a function called `arpeggiate` that can take a chord, scale, or array of notes.  If you'd like to do that and make a PR, that would also be welcome.  Otherwise, I'll probably do it when I have some free time.

**Comment by raff** [comment]
Great! I'll prepare a PR.

Thanks!

-- Raffaele
